apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trustchain
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/YOUR_GITHUB/trustchain-playground.git
    targetRevision: main
    path: helm/trustchain
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: trustchain
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
